# Generated by Django 4.2.18 on 2025-02-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_file_remove_uploadedfile_file_uploadedfile_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='files',
            field=models.ManyToManyField(related_name='uploaded_files', to='upload.file'),
        ),
    ]
